import { app, BrowserWindow } from 'electron';
import path from 'path';
import express from 'express';
import http from 'http';
import { fileURLToPath } from 'url';

// Handle __dirname in ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let mainWindow;
let server;
let serverPort = 34567; // Default port, can be dynamic if using get-port

const startServer = async () => {
    const expressApp = express();
    // Serve the 'dist' directory generated by Vite (sibling to 'electron' folder)
    const distPath = path.join(__dirname, '../dist');
    
    expressApp.use(express.static(distPath));
    
    // SPA Fallback: Redirect all 404s to index.html
    expressApp.get('*', (req, res) => {
        res.sendFile(path.join(distPath, 'index.html'));
    });

    server = http.createServer(expressApp);
    
    return new Promise((resolve) => {
        server.listen(serverPort, () => {
            console.log(`Local server running on port ${serverPort}`);
            resolve();
        });
    });
};

const createWindow = () => {
    mainWindow = new BrowserWindow({
        width: 1280,
        height: 800,
        title: "Pedro Pathing Visualizer",
        webPreferences: {
            nodeIntegration: false, // Security: Sandbox the web code
            contextIsolation: true, // Security: Sandbox the web code
            preload: path.join(__dirname, 'preload.js')
        }
    });

    // Load the app from the local server
    mainWindow.loadURL(`http://localhost:${serverPort}`);

    // Handle "Save As" dialog native behavior [cite: 672]
    mainWindow.webContents.session.on('will-download', (event, item, webContents) => {
        item.setSavePathDialog(true);
        item.on('updated', (event, state) => {
            if (state === 'interrupted') {
                console.log('Download is interrupted but can be resumed');
            }
        });
    });

    mainWindow.on('closed', () => {
        mainWindow = null;
    });
};

app.on('ready', async () => {
    await startServer();
    createWindow();
});

// CRITICAL: Satisfies "when the project closes it should auto close" [cite: 647]
app.on('window-all-closed', () => {
    app.quit();
});

app.on('will-quit', () => {
    if (server) {
        server.close();
    }
});